Maximum and Mode added
MajorTreble/Metricstics pull request #15
Opened 2023-11-05 23:17 UTC by Protim-Proshun

Maximum and mode added to the calculation, input_controller, view

2023-11-06 01:59 UTC, MajorTreble requested changes

2023-11-06 01:59 UTC, MajorTreble commented on metricstics/src/controller/input_controller.py
> +        def view_maximum(self):
Why is called view? It should not be indented.

2023-11-06 01:59 UTC, MajorTreble commented on metricstics/src/controller/input_controller.py
> +    def view_mode(self):
Why is it called view?

2023-11-06 01:59 UTC, MajorTreble commented on metricstics/src/model/calculation.py
> +        def view_maximum(self, data, result):
Should not be indented or called view.

2023-11-06 01:59 UTC, MajorTreble commented on metricstics/src/model/calculation.py
> +        maximum = data[0]
What if size is 0?

2023-11-06 01:59 UTC, MajorTreble commented on metricstics/src/model/calculation.py
> +    def view_mode(self, data, result):
Should not be called view

2023-11-06 01:59 UTC, MajorTreble commented on metricstics/src/model/calculation.py
> +        for i in data:
What if size is 0?

2023-11-06 01:59 UTC, MajorTreble commented on metricstics/src/model/calculation.py
> +            result["Mode"] = 0
Why 0?

2023-11-06 01:59 UTC, MajorTreble commented on metricstics/src/view/view.py
> +        '''self.button_vmx = Button(self, text="View Maximum", borderless=1)
Don't submit commented code

2023-11-08 10:29 UTC, Protim-Proshun commented on metricstics/src/model/calculation.py
> +        maximum = data[0]
it will return 0

2023-11-08 10:30 UTC, Protim-Proshun commented on metricstics/src/model/calculation.py
> +            result["Mode"] = 0
if there is no reparation of any number the mode becomes "0"

2023-11-10 21:19 UTC, MajorTreble commented on metricstics/src/model/calculation.py
> +        maximum = data[0]
if size is 0, you can return early without doing the for loop

2023-11-10 21:20 UTC, MajorTreble commented on metricstics/src/model/calculation.py
> +        for i in data:
same here, return early

2023-11-10 21:23 UTC, MajorTreble commented on metricstics/src/model/calculation.py
> +            result["Mode"] = 0
An empty set does not have a mean so it is an error.

2023-11-10 21:25 UTC, MajorTreble approved these changes

2023-11-12 13:10 UTC, Protim-Proshun commented on metricstics/src/model/calculation.py
> +        for i in data:
Done

2023-11-13 18:59 UTC, merged